# Generated by Django 2.2.6 on 2019-12-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('pelapor', models.CharField(max_length=20)),
                ('daerah', models.CharField(max_length=30)),
                ('kategori', models.CharField(max_length=30)),
            ],
        ),
    ]
