# Generated by Django 2.2.6 on 2019-12-12 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laporan',
            name='deskripsi',
            field=models.TextField(blank=True, default='Deskripsi Kosong', null=True),
        ),
    ]
