# Generated by Django 2.2.6 on 2019-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_auto_20191212_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sudah Masuk'), (2, 'Ditanggapi'), (3, 'Sedang Dikerjakan'), (4, 'Selesai')], default=0),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waktu Submit'),
        ),
    ]
