# Generated by Django 2.2.6 on 2019-12-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0006_auto_20191213_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporan',
            name='daerah',
        ),
    ]
