# Generated by Django 2.2.6 on 2019-12-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20191213_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasitambahanuser',
            name='nik',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
